apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: prometheus
  name: prometheus-volume
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-06683a86b1b1c97e3
    fsType: ext4




apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: loki
  name: prometheus-volume
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-06683a86b1b1c97e3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.ebs.csi.aws.com/zone
              operator: In
              values:
                - eu-west-1b


