---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: files
    env: test
  name: files-volume-test
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-0d9cfa585192d8a94.efs.eu-west-1.amazonaws.com
    path: /
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    type: files
    env: test
  name: files-volume-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: "files"
      env: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  selector:
    matchLabels:
      service: MyCluster-service2
  template:
    metadata:
      labels:
        service: MyCluster-service2
    spec:
      containers:
        - image: busybox:latest
          args:
            - sleep
            - "1000000"
          name: busy
          volumeMounts:
            - name: files-data
              mountPath: /storage

      volumes:
        - name: files-data
          persistentVolumeClaim:
            claimName: files-volume-claim
