kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zabbix
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "list"]