apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: eu-west-1

managedNodeGroups:
  - name: spot
    instanceTypes: ["t3a.medium"]
    availabilityZones: ["eu-west-1b"]
    privateNetworking: true
    spot: true
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    maxPodsPerNode: 54
    labels: {role: "spot"}
    tags:
      nodegroup-role: worker